### ISSUE TITLE
The integrated mime reader start always first

### ISSUE THREAD

**Issue by CloudyLord** [manitou-mail/manitou-mail-ui#4]
Hi,

When I choose Thunderbird as my default reader for mime rfc822 message nothing happens.
It's always the default reader in Manitou-Mail which starts.
Can we imagine that the users choice be the first considered?

Regards,

**Comment by manitou-mail** [comment]
Yes, this is fixed in commit 663d907
Also when called with the mailfile to view as argument, thunderbird needs it to be like `filename.eml`, otherwise it seems to take it as an attachment to send.
This can be declared to manitou in the database with the SQL command:
  `INSERT INTO mime_types(suffix,mime_type) VALUES ('eml', 'message/rfc822');`
which has to be done manually for an already existing db.
